### ISSUE TITLE
Update to Node 12

### ISSUE THREAD

**Issue by bplaster** [AraBlocks/ara-context#15]
## Expected Behavior
Functions with Node 12. 

## Actual Behavior
Various security vulnerabilities and incompatibility with Node 12 (the latest version of electron).

**Comment by bplaster** [comment]
@jwerle can you take a look at the test that is causing this to fail: 
https://travis-ci.com/github/AraBlocks/ara-context/builds/216310370

**Comment by jwerle** [comment]
yeah ill try to look this week
