### ISSUE TITLE
Web3 provider not found if only network_id given

### ISSUE THREAD

**Issue by cckelly** [AraBlocks/ara-context#9]
## Expected Behavior

As a user, I should just be able to provide `network_id` to receive a valid `Web3` object.

## Actual Behavior

If only given a `network_id` string without a `provider` in `ararc`, the error message `An unknown error occured: Unable to resolve a Web3 provider` is thrown.

**Comment by vipyne** [comment]
closed with https://github.com/AraBlocks/ara-filesystem/pull/158
